project_id = "hpmcbosuvmujhljdccui"

[functions.send-message-notification]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.send-notice-notification]
verify_jwt = false